# Generated by Django 4.0.4 on 2022-05-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='facebookLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagramLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitterLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='youtubeLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
