# Generated by Django 4.0.4 on 2022-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0002_alter_teammember_facebooklink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
