# Generated by Django 4.0.4 on 2022-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0003_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='githubLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
