# Generated by Django 4.0.4 on 2022-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0004_teammember_githublink'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedinLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
