# Generated by Django 4.0.4 on 2022-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0005_teammember_linkedinlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('NEWS', 'BLOG'), ('NEWS', 'BLOG')], default='BLOG', max_length=10),
        ),
    ]
