# Generated by Django 4.0.4 on 2022-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0006_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('BLOG', 'Blog')], default='BLOG', max_length=10),
        ),
    ]
